services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongodb
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - MONGO_URI=mongodb://mongodb:27017

  redis:
    image: "redis:6.2"
    ports:
      - "6379:6379"

  celery:
    build: .
    command: poetry run celery -A app.celery_app worker --loglevel=info
    depends_on:
      - redis
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
